swagger: "2.0"
info:
  version: "1.0.0"
  title: App microservice for checkout authentication
tags:
  - name: Checkout Authentication
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /rest/services/v1/apps/checkout-auth/otpmessage:
    post:
      tags:
        - "Checkout Authentication"
      operationId: generateOtp
      consumes:
        - application/json
      parameters:
        - in: query
          name: idNumber
          type: string
          required: true
        - in: query
          name: docType
          type: string
          required: true
        - in: "query"
          name: maskedMsisdn
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/OtpStatus"
        400:
          description: Missing required input parameter
        401:
          description: Not authorized
        424:
          description: Upstream call failed with a 500. Response will be identical to upstream failure
        500:
          description: Technical error occured, service failure.
  /swagger:
    x-swagger-pipe: swagger_raw

# complex objects have schema definitions
definitions:
  OtpStatus:
    type: object
    properties:
      messages:
        type: array
        items:
          type: string
      result:
        type: object
        properties:
          sendAttempts:
            type: number
          links:
            type: array
            items:
              $ref: "#/definitions/Link"
      successful:
        type: boolean
      code:
        type: number

  Link:
    type: object
    properties:
      href:
        type: string
        xml:
          name: href
          attribute: true
          wrapped: false
      rel:
        type: string
        xml:
          name: rel
          attribute: true
          wrapped: false
      templated:
        type: boolean
    title: Link

